### ISSUE TITLE
Error downloading model file（mobile_human_pose_working_well_256x256.onnx）？

### ISSUE THREAD

**Issue by shnulailai** [ibaiGorordo/ONNX-Mobile-Human-Pose-3D#1]
I can't download through the link（https://github.com/PINTO0309/PINTO_model_zoo/blob/main/135_CoEx/download.sh）.The error screenshot is as follows：
![09d4da6e7f4c29ed57d53742fc38d16](https://user-images.githubusercontent.com/28287142/134860184-442053ea-42ef-46f4-85f5-5230a4741e6e.png)
，I can not find the cookie file.Can you provide an absolute download link，thank you.

**Comment by ibaiGorordo** [comment]
Which model are you trying to download?

Anyway, you can open the file in the browser and copy the google drive link directly in the browser to download it manually:

For the mobile human pose:
curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=1vvjUsP_41Nqhj8oqRw2OpWjIdz8t5fxG" > /dev/null

For the Yolov5s:
https://drive.google.com/uc?export=download&id=11D7b_D5Ksknc1ZgHHfMG10zvvmgHEa_C

**Comment by shnulailai** [comment]
Thank you for your answer, I have already downloaded these two model files.

**Comment by BYLinMou** [comment]
Hi,

The Google Drive links you shared earlier seem to have expired or are no longer available. Could you please provide updated download links for the models? Thanks a lot!

**Comment by shnulailai** [comment]
您的来信我已经收到了！
