### ISSUE TITLE
Inference problem 

### ISSUE THREAD

**Issue by SienChen1997** [ibaiGorordo/ONNX-Mobile-Human-Pose-3D#2]
Hi,thanks for the great work. I follow your Readme and download the required models including Mobile Human Pose and YOLOv5s, and below is the inference result and which is not as accurate as i expect.
The input image size is 512*512, and i have no idea to choose the proper detection model(different resolution),so i just tried it all,which not improved the result.Could you point out what the problem is?

![output](https://user-images.githubusercontent.com/14939586/136959913-347adbbf-7271-4f9f-8cc5-64f8eb037206.png)

**Comment by ibaiGorordo** [comment]
I am sorry for the delay. I have not forgotten, but I am planning to release an inference script for a more accurate model soon that might fix your issue. I have been getting distracted with other projects, but I want to get it working by the end of this week.

**Comment by chandelarvind** [comment]
@SienChen1997 @ibaiGorordo I am trying model on live / image data, and keypoints quality is like above only. Any suggestion how i can better results.
